### ISSUE TITLE
Crashed after bridgefy started

### ISSUE THREAD

**Issue by qhd12345** [bridgefy/sdk-android-beta#2]
I init and start bridgefy and got this error:

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ProcessLifecycleOwner;
        at me.bridgefy.transport.ble.transport.BLETransport$a.invokeSuspend(SourceFile:2)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@22c0fa, Dispatchers.Main]
    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ProcessLifecycleOwner" on path: DexPathList[[dex file "/data/data/com.ebsl.ptsmci/code_cache/.overlay/base.apk/classes6.dex", zip file "/data/app/~~ZfjAGms5Son2wDCSjZZUGQ==/com.ebsl.ptsmci-vs8TYE-PyNzZMSpga5l-NA==/base.apk"],nativeLibraryDirectories=[/data/app/~~ZfjAGms5Son2wDCSjZZUGQ==/com.ebsl.ptsmci-vs8TYE-PyNzZMSpga5l-NA==/lib/arm64, /data/app/~~ZfjAGms5Son2wDCSjZZUGQ==/com.ebsl.ptsmci-vs8TYE-PyNzZMSpga5l-NA==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 10 more

Here are my code:
```
class A {
    lateinit var bridgefy: Bridgefy
    val connected = `hashSetOf<UUID>()`
    private val delegate = object : BridgefyDelegate {
        override fun onConnected(userID: UUID) {
            logD("Bridgefy. onConnected:${userID}")
            connected.add(userID)
        }

        override fun onConnectedSecurely(userID: UUID) {
            logD("Bridgefy. onConnectedSecurely:${userID}")
        }

        override fun onDisconnected(userID: UUID) {
            logD("Bridgefy. onDisconnected:${userID}")
            connected.remove(userID)
        }

        override fun onFailToSend(messageID: UUID) {
            logD("Bridgefy. onFailToSend:${messageID}")
        }

        override fun onFailToStart(error: BridgefyException) {
            logE("Bridgefy. onFailToStart:${error.message}")
        }

        override fun onReceive(data: ByteArray, messageID: UUID, transmissionMode: TransmissionMode) {
            logD("Bridgefy. onReceive:${data} from:${messageID}")
        }

        override fun onSend(messageID: UUID) {
            logD("Bridgefy. onSend:${messageID}")
        }

        override fun onStarted(userID: UUID) {
            logD("Bridgefy. onStarted:${userID}")
        }
    }

    fun start(activity: BaseActivity) {
        if (!(isBluetoothEnable() && isGPSEnable(activity))) {
            return
        }
        bridgefy = Bridgefy(activity)
        try {
            bridgefy.init("be5c5b91-af44-408c-84dc-108560c7e7b5", delegate = delegate)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
```
**Smartphone (please complete the following information):**
 - Device: Galaxy XCover 5
 - OS: Android 11

**Comment by julian-bridgefy** [comment]
Hello [qhd12345](https://github.com/qhd12345),  you have missed out on adding the `androidx.lifecycle:lifecycle-process` or `androidx.appcompat:appcompat` dependency in your application and the issue should be fixed.
