### ISSUE TITLE
Android devices not connecting nearby via Beta SDK.

### ISSUE THREAD

**Issue by mesrob-crew** [bridgefy/sdk-android-beta#4]
**Describe the bug**
Two Android devices are not connecting with each other using Beta SDK.

**To Reproduce**
1. Start SDK on two Android devices.
2. The `onStarted` delegate callback was called for both devices with their User UUID shown below in the logs.
3. No connection between devices.

**Expected behavior**
I expect each device to connect with one another.

**Logs**
Moto G Play Logs: 
```
[        ] D/BluetoothAdapter( 9177): isLeEnabled(): ON
[        ] D/BluetoothGattServer( 9177): registerCallback() - UUID=629ba903-b016-4913-bfe7-275c287ed496
[   +4 ms] D/BluetoothLeScanner( 9177): onScannerRegistered() - status=0 scannerId=8 mScannerId=0
[        ] D/BluetoothGattServer( 9177): onServerRegistered() - status=0 serverIf=9
[        ] D/BluetoothGattServer( 9177): addService() - service: bc50444b-ee25-ec5f-c290-0553ed169d0d
[   +8 ms] D/BluetoothAdapter( 9177): isLeEnabled(): ON
[   +4 ms] D/BluetoothGattServer( 9177): onServiceAdded() - handle=40 uuid=bc50444b-ee25-ec5f-c290-0553ed169d0d status=0
[   +1 ms] D/BluetoothAdapter( 9177): isLeEnabled(): ON
[+3454 ms] I/flutter ( 9177): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[        ] I/flutter ( 9177): │ #0   _MyAppState.onStarted (package:bridgefy_flutter_example/main.dart:153:12)
[        ] I/flutter ( 9177): │ #1   DelegateHandler._foregroundHandler (package:bridgefy_flutter/delegate_handler.dart:170:18)
[        ] I/flutter ( 9177): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] I/flutter ( 9177): │ 🐛 On Started with 9f05cdae-bb5b-4ef6-94b9-7c8a007734a3
[        ] I/flutter ( 9177): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[+2968 ms] D/BluetoothGatt( 9177): connect() - device: 4E:EE:38:33:AB:5E, auto: true
[        ] D/BluetoothGatt( 9177): registerApp()
[        ] D/BluetoothGatt( 9177): registerApp() - UUID=5c833615-d844-4c0e-9cd3-50fb666cdba7
[  +20 ms] D/BluetoothGatt( 9177): onClientRegistered() - status=0 clientIf=10
[+4152 ms] E/ScanRecord( 9177): unable to parse scan record: [4, -99, 97, -41, 77, 127]
[   +5 ms] E/ScanRecord( 9177): unable to parse scan record: [-33, 31, 77, 110, -92, 65]
[+11025 ms] E/ScanRecord( 9177): unable to parse scan record: [-98, 33, 31, 97, -35, 109]
[   +1 ms] E/ScanRecord( 9177): unable to parse scan record: [79, 8, 74, -65, -27, 81]
[+5701 ms] E/ScanRecord( 9177): unable to parse scan record: [95, 7, -92, -94, 120, 95]
[   +9 ms] E/ScanRecord( 9177): unable to parse scan record: [95, 7, -92, -94, 120, 95]
```

Pixel 3 Logs:
```
[        ] D/BluetoothAdapter( 9177): isLeEnabled(): ON
[        ] D/BluetoothGattServer( 9177): registerCallback() - UUID=629ba903-b016-4913-bfe7-275c287ed496
[   +4 ms] D/BluetoothLeScanner( 9177): onScannerRegistered() - status=0 scannerId=8 mScannerId=0
[        ] D/BluetoothGattServer( 9177): onServerRegistered() - status=0 serverIf=9
[        ] D/BluetoothGattServer( 9177): addService() - service: bc50444b-ee25-ec5f-c290-0553ed169d0d
[   +8 ms] D/BluetoothAdapter( 9177): isLeEnabled(): ON
[   +4 ms] D/BluetoothGattServer( 9177): onServiceAdded() - handle=40 uuid=bc50444b-ee25-ec5f-c290-0553ed169d0d status=0
[   +1 ms] D/BluetoothAdapter( 9177): isLeEnabled(): ON
[+3454 ms] I/flutter ( 9177): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[        ] I/flutter ( 9177): │ #0   _MyAppState.onStarted (package:bridgefy_flutter_example/main.dart:153:12)
[        ] I/flutter ( 9177): │ #1   DelegateHandler._foregroundHandler (package:bridgefy_flutter/delegate_handler.dart:170:18)
[        ] I/flutter ( 9177): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] I/flutter ( 9177): │ 🐛 On Started with 9f05cdae-bb5b-4ef6-94b9-7c8a007734a3
[        ] I/flutter ( 9177): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[+2968 ms] D/BluetoothGatt( 9177): connect() - device: 4E:EE:38:33:AB:5E, auto: true
[        ] D/BluetoothGatt( 9177): registerApp()
[        ] D/BluetoothGatt( 9177): registerApp() - UUID=5c833615-d844-4c0e-9cd3-50fb666cdba7
[  +20 ms] D/BluetoothGatt( 9177): onClientRegistered() - status=0 clientIf=10
[+4152 ms] E/ScanRecord( 9177): unable to parse scan record: [4, -99, 97, -41, 77, 127]
[   +5 ms] E/ScanRecord( 9177): unable to parse scan record: [-33, 31, 77, 110, -92, 65]
[+11025 ms] E/ScanRecord( 9177): unable to parse scan record: [-98, 33, 31, 97, -35, 109]
[   +1 ms] E/ScanRecord( 9177): unable to parse scan record: [79, 8, 74, -65, -27, 81]
[+5701 ms] E/ScanRecord( 9177): unable to parse scan record: [95, 7, -92, -94, 120, 95]
[   +9 ms] E/ScanRecord( 9177): unable to parse scan record: [95, 7, -92, -94, 120, 95]
```

**Smartphone (please complete the following information):**
 - Device: [Pixel 3, Moto G Play]
 - OS: [Android, Android]
 - Version [12, 11]

**Additional context**
Testing through a Flutter interface.

**Comment by julian-bridgefy** [comment]
Hi [mesrob-crew](https://github.com/mesrob-crew) we are working on improving the communication and adding new features, thanks for the report, it is an unstable behavior that we are improving in the next version. For now, you can try reinstalling the app until **Pixel 3** tries to connect to **Moto G Play** and see what happens.

**Comment by julian-bridgefy** [comment]
Improvements have been made in version `0.2.0-SNAPSHOT`, connections, Mesh/Broadcast and sending direct messages.
