### ISSUE TITLE
Getting NoClassDefFoundError when initializing

### ISSUE THREAD

**Issue by qhd12345** [bridgefy/sdk-android-beta#9]
**Describe the bug**
I am testing the Android SDK. Getting NoClassDefFoundError when initializing. None of the delegate callbacks are getting invoked.

**To Reproduce**
1. Call bridgefy.init()

**Expected behavior**
To initialize the SDK and call the onStarted() delegate callback.

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: samsung SM-G525F
 - OS: Android
 - Version 11

**Additional context**
Logs:
E/BridgefyBluetoothManager -> log: samsung SM-G525F Android SDK version 30 +9
     Device can act as a client and a server +1
     Device can filter unwanted interference +1
     Device can batch scan results +1
     Device supports Bluetooth 5 LE Coded PHY features +1 
     Device supports Bluetooth 5 LE 2M PHY features +1 
     Device supports Bluetooth 5 Extended Advertising +1 
     Device supports Bluetooth 5 Periodic Advertising +1 
     Device can reset ongoing scans without side effects +1
W/BridgefyBluetoothManager -> log: DeviceSupportsAllCharacteristics
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.ebsl.ptsmci, PID: 9029
    java.lang.NoClassDefFoundError: Failed resolution of: Lme/bridgefy/analytics/worker/AnalyticsBackgroundTask;
        at me.bridgefy.analytics.internal.AnalyticsManagerImpl.initAnalyticsWorker(SourceFile:5)
        at me.bridgefy.session.internal.SessionManagerImpl.start(SourceFile:4)
        at me.bridgefy.internal.BridgefyManager$a$a.invoke(SourceFile:5)
        at me.bridgefy.session.internal.SessionManagerImpl$b.invoke(SourceFile:7)
        at me.bridgefy.license.internal.LicenseManagerImpl$a$b.invoke(SourceFile:4)
        at e.a.invokeSuspend(SourceFile:6)
        at e.a.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at me.bridgefy.license.internal.LicenseManagerImpl.access$buildBridgefyLicense(SourceFile:2)
        at me.bridgefy.license.internal.LicenseManagerImpl$a.invokeSuspend(SourceFile:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dd1c5b8, Dispatchers.IO]
    Caused by: java.lang.ClassNotFoundException: me.bridgefy.analytics.worker.AnalyticsBackgroundTask
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 20 more
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/CoroutineWorker;
        	... 20 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.work.CoroutineWorker" on path: DexPathList[[zip file "/data/app/~~MxBtE5_AEMR2anLXzJ0VYg==/com.ebsl.ptsmci-LoUOvYWbZaaISrH7CRrvSg==/base.apk"],nativeLibraryDirectories=[/data/app/~~MxBtE5_AEMR2anLXzJ0VYg==/com.ebsl.ptsmci-LoUOvYWbZaaISrH7CRrvSg==/lib/arm64, /data/app/~~MxBtE5_AEMR2anLXzJ0VYg==/com.ebsl.ptsmci-LoUOvYWbZaaISrH7CRrvSg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 20 more

And in my project level build.gradle:
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            url "http://104.196.228.98:8081/artifactory/libs-snapshot-local"
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = "bridgefy-beta"
                password = "g\$thaP@ad8w=w=OT78_r"
            }
            allowInsecureProtocol = true
        }
    }
}
```

in app level build.gradle:
```
implementation ("me.bridgefy:android-sdk:0.2.0-SNAPSHOT@aar") {
        transitive = true
    }
```

**Comment by qhd12345** [comment]
I just missing the androidx.work:work-runtime-ktx dependency. Is fine now.
